from __future__ import annotations

import json
from typing import Any

from .config import load_config

#: Postgres DDL. Every Garmin-data table carries ``user_id`` as the leading
#: primary-key column so Row-Level Security can scope every row to one account.
#: ``raw_json`` stays TEXT — the payloads are only ever written/read whole via
#: ``json.dumps``/``loads``, so JSONB would buy nothing today.
_SCHEMA_PG = """
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    garmin_email TEXT NOT NULL,
    garmin_cred_enc TEXT,
    tokens_enc TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TEXT NOT NULL,
    last_sync_at TEXT,
    sync_error TEXT,
    sync_fail_count INTEGER NOT NULL DEFAULT 0,
    rate_limit_until TEXT,
    llm_api_key_enc TEXT,
    llm_base_url TEXT,
    llm_model TEXT,
    home_lat TEXT,
    home_lon TEXT,
    excluded_data_types TEXT,
    sync_start_date TEXT
);

CREATE TABLE IF NOT EXISTS user_state (
    user_id BIGINT NOT NULL,
    key TEXT NOT NULL,
    value TEXT,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (user_id, key)
);

CREATE TABLE IF NOT EXISTS metrics (
    user_id BIGINT NOT NULL,
    data_type TEXT NOT NULL,
    calendar_date TEXT NOT NULL,
    raw_json TEXT NOT NULL,
    fetched_at TEXT NOT NULL,
    parsed_at TEXT,
    PRIMARY KEY (user_id, data_type, calendar_date)
);
CREATE INDEX IF NOT EXISTS idx_metrics_user_type_date
    ON metrics (user_id, data_type, calendar_date);

CREATE TABLE IF NOT EXISTS activities (
    user_id BIGINT NOT NULL,
    activity_id BIGINT NOT NULL,
    raw_json TEXT NOT NULL,
    fetched_at TEXT NOT NULL,
    details_json TEXT,
    details_fetched_at TEXT,
    weather_json TEXT,
    weather_fetched_at TEXT,
    splits_json TEXT,
    splits_fetched_at TEXT,
    summary_parsed_at TEXT,
    details_parsed_at TEXT,
    weather_parsed_at TEXT,
    splits_parsed_at TEXT,
    PRIMARY KEY (user_id, activity_id)
);

CREATE TABLE IF NOT EXISTS sync_state (
    user_id BIGINT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    PRIMARY KEY (user_id, key)
);

CREATE TABLE IF NOT EXISTS daily_metrics (
    user_id BIGINT NOT NULL,
    calendar_date TEXT NOT NULL,
    fetched_at TEXT,
    PRIMARY KEY (user_id, calendar_date)
);

CREATE TABLE IF NOT EXISTS activity_summaries (
    user_id BIGINT NOT NULL,
    activity_id BIGINT NOT NULL,
    activity_name TEXT,
    activity_type TEXT,
    start_time_local TEXT,
    end_time_local TEXT,
    start_date TEXT,
    duration_hours DOUBLE PRECISION,
    elapsed_hours DOUBLE PRECISION,
    moving_hours DOUBLE PRECISION,
    distance_km DOUBLE PRECISION,
    avg_hr DOUBLE PRECISION,
    max_hr DOUBLE PRECISION,
    hr_time_zone_1_pct DOUBLE PRECISION,
    hr_time_zone_2_pct DOUBLE PRECISION,
    hr_time_zone_3_pct DOUBLE PRECISION,
    hr_time_zone_4_pct DOUBLE PRECISION,
    hr_time_zone_5_pct DOUBLE PRECISION,
    calories DOUBLE PRECISION,
    training_load DOUBLE PRECISION,
    aerobic_training_effect DOUBLE PRECISION,
    anaerobic_training_effect DOUBLE PRECISION,
    moderate_intensity_minutes DOUBLE PRECISION,
    vigorous_intensity_minutes DOUBLE PRECISION,
    elevation_gain_m DOUBLE PRECISION,
    elevation_loss_m DOUBLE PRECISION,
    min_elevation_m DOUBLE PRECISION,
    max_elevation_m DOUBLE PRECISION,
    avg_speed_kmh DOUBLE PRECISION,
    max_speed_kmh DOUBLE PRECISION,
    pace_min_km DOUBLE PRECISION,
    min_respiration_rate DOUBLE PRECISION,
    avg_respiration_rate DOUBLE PRECISION,
    max_respiration_rate DOUBLE PRECISION,
    body_battery_change DOUBLE PRECISION,
    water_estimated_ml DOUBLE PRECISION,
    is_pr BOOLEAN,
    avg_cadence DOUBLE PRECISION,
    max_cadence DOUBLE PRECISION,
    avg_power_w DOUBLE PRECISION,
    max_power_w DOUBLE PRECISION,
    norm_power_w DOUBLE PRECISION,
    vo2max DOUBLE PRECISION,
    power_time_zone_1_pct DOUBLE PRECISION,
    power_time_zone_2_pct DOUBLE PRECISION,
    power_time_zone_3_pct DOUBLE PRECISION,
    power_time_zone_4_pct DOUBLE PRECISION,
    power_time_zone_5_pct DOUBLE PRECISION,
    avg_stride_length_cm DOUBLE PRECISION,
    avg_vertical_oscillation_cm DOUBLE PRECISION,
    avg_ground_contact_time_ms DOUBLE PRECISION,
    avg_vertical_ratio_pct DOUBLE PRECISION,
    weather_temp_c DOUBLE PRECISION,
    weather_apparent_c DOUBLE PRECISION,
    weather_humidity DOUBLE PRECISION,
    weather_wind_kmh DOUBLE PRECISION,
    weather_description TEXT,
    fetched_at TEXT,
    PRIMARY KEY (user_id, activity_id)
);

CREATE TABLE IF NOT EXISTS activity_detail_series (
    user_id BIGINT NOT NULL,
    activity_id BIGINT NOT NULL,
    tick BIGINT NOT NULL,
    ts_ms DOUBLE PRECISION,
    heart_rate DOUBLE PRECISION,
    cadence DOUBLE PRECISION,
    power_w DOUBLE PRECISION,
    speed_kmh DOUBLE PRECISION,
    elevation_m DOUBLE PRECISION,
    distance_m DOUBLE PRECISION,
    respiration_rate DOUBLE PRECISION,
    accumulated_power_w DOUBLE PRECISION,
    PRIMARY KEY (user_id, activity_id, tick)
);

CREATE TABLE IF NOT EXISTS user_profile (
    user_id BIGINT NOT NULL,
    profile_type TEXT NOT NULL,
    raw_json TEXT NOT NULL,
    fetched_at TEXT NOT NULL,
    PRIMARY KEY (user_id, profile_type)
);

CREATE TABLE IF NOT EXISTS hr_zones (
    user_id BIGINT NOT NULL,
    sport TEXT NOT NULL,
    training_method TEXT,
    zone1_min DOUBLE PRECISION,
    zone1_max DOUBLE PRECISION,
    zone2_min DOUBLE PRECISION,
    zone2_max DOUBLE PRECISION,
    zone3_min DOUBLE PRECISION,
    zone3_max DOUBLE PRECISION,
    zone4_min DOUBLE PRECISION,
    zone4_max DOUBLE PRECISION,
    zone5_min DOUBLE PRECISION,
    zone5_max DOUBLE PRECISION,
    max_hr_used DOUBLE PRECISION,
    resting_hr_used DOUBLE PRECISION,
    lactate_threshold_hr_used DOUBLE PRECISION,
    resting_hr_auto_update BOOLEAN,
    fetched_at TEXT,
    PRIMARY KEY (user_id, sport)
);

CREATE TABLE IF NOT EXISTS race_predictions (
    user_id BIGINT NOT NULL,
    calendar_date TEXT NOT NULL,
    time_5k_min DOUBLE PRECISION,
    time_10k_min DOUBLE PRECISION,
    time_half_marathon_min DOUBLE PRECISION,
    time_marathon_min DOUBLE PRECISION,
    fetched_at TEXT,
    PRIMARY KEY (user_id, calendar_date)
);

CREATE TABLE IF NOT EXISTS gear (
    user_id BIGINT NOT NULL,
    gear_uuid TEXT NOT NULL,
    gear_type TEXT,
    name TEXT,
    total_distance_km DOUBLE PRECISION,
    activity_count BIGINT,
    last_activity_date TEXT,
    retired BOOLEAN,
    fetched_at TEXT,
    PRIMARY KEY (user_id, gear_uuid)
);

CREATE TABLE IF NOT EXISTS activity_splits (
    user_id BIGINT NOT NULL,
    activity_id BIGINT NOT NULL,
    split_type TEXT NOT NULL,
    split_number INTEGER NOT NULL,
    distance_m DOUBLE PRECISION,
    duration_s DOUBLE PRECISION,
    start_time_s DOUBLE PRECISION,
    pace_sec_per_km DOUBLE PRECISION,
    avg_hr DOUBLE PRECISION,
    max_hr DOUBLE PRECISION,
    avg_power DOUBLE PRECISION,
    max_power DOUBLE PRECISION,
    avg_cadence DOUBLE PRECISION,
    max_cadence DOUBLE PRECISION,
    elevation_gain_m DOUBLE PRECISION,
    PRIMARY KEY (user_id, activity_id, split_type, split_number)
);

CREATE TABLE IF NOT EXISTS power_zones (
    user_id BIGINT NOT NULL,
    sport TEXT NOT NULL,
    zone1_min DOUBLE PRECISION,
    zone1_max DOUBLE PRECISION,
    zone2_min DOUBLE PRECISION,
    zone2_max DOUBLE PRECISION,
    zone3_min DOUBLE PRECISION,
    zone3_max DOUBLE PRECISION,
    zone4_min DOUBLE PRECISION,
    zone4_max DOUBLE PRECISION,
    zone5_min DOUBLE PRECISION,
    zone5_max DOUBLE PRECISION,
    zone6_min DOUBLE PRECISION,
    zone6_max DOUBLE PRECISION,
    zone7_min DOUBLE PRECISION,
    zone7_max DOUBLE PRECISION,
    functional_threshold_power DOUBLE PRECISION,
    fetched_at TEXT,
    PRIMARY KEY (user_id, sport)
);

CREATE TABLE IF NOT EXISTS devices (
    user_id BIGINT NOT NULL,
    device_id BIGINT NOT NULL,
    model_name TEXT,
    display_name TEXT,
    fetched_at TEXT,
    PRIMARY KEY (user_id, device_id)
);

CREATE TABLE IF NOT EXISTS derived_metrics (
    user_id BIGINT NOT NULL,
    calendar_date TEXT NOT NULL,
    metric TEXT NOT NULL,
    value DOUBLE PRECISION,
    qualifier TEXT,
    fetched_at TEXT,
    PRIMARY KEY (user_id, calendar_date, metric)
);

CREATE TABLE IF NOT EXISTS training_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    planned_date TEXT NOT NULL,
    activity_type TEXT NOT NULL,
    title TEXT,
    description TEXT,
    duration_min INTEGER,
    distance_km DOUBLE PRECISION,
    intensity TEXT,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_activity_id BIGINT,
    created_at TEXT,
    updated_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_training_plan_user_date
    ON training_plan (user_id, planned_date);
"""

#: Tables whose rows are scoped per account. ``users`` (the identity table) is
#: deliberately excluded — the auth layer needs to read every row.
_RLS_TABLES = (
    "metrics", "activities", "sync_state", "daily_metrics",
    "activity_summaries", "activity_detail_series", "activity_splits",
    "user_profile", "hr_zones", "power_zones", "race_predictions", "gear",
    "devices", "derived_metrics", "user_state", "training_plan",
)

#: Tables the read-only agent role may SELECT (the "allowed tables"). Everything
#: else is a real REVOKE at the database level, not a regex.
_AGENT_TABLES = (
    "daily_metrics", "activity_summaries", "activity_detail_series",
    "activity_splits", "hr_zones", "power_zones", "race_predictions", "gear",
    "devices", "derived_metrics", "training_plan",
)

#: PG types for columns that a legacy/fresh-enough Postgres DB might be missing
#: (``_ensure_columns`` migration on the PG side; a brand-new PG schema already
#: carries every column, so this only fires when a column is added later).
_PG_MIGRATION_TYPES: dict[str, dict[str, str]] = {
    "activities": {
        "details_json": "TEXT",
        "details_fetched_at": "TEXT",
        "weather_json": "TEXT",
        "weather_fetched_at": "TEXT",
        "splits_json": "TEXT",
        "splits_fetched_at": "TEXT",
        "summary_parsed_at": "TEXT",
        "details_parsed_at": "TEXT",
        "weather_parsed_at": "TEXT",
        "splits_parsed_at": "TEXT",
    },
    "metrics": {"parsed_at": "TEXT"},
    "training_plan": {"completed_activity_id": "BIGINT"},
    "activity_summaries": {
        "activity_name": "TEXT",
        "activity_type": "TEXT",
        "start_time_local": "TEXT",
        "end_time_local": "TEXT",
        "start_date": "TEXT",
        "pace_min_km": "DOUBLE PRECISION",
        "weather_description": "TEXT",
        "is_pr": "BOOLEAN",
    },
}


def _pg_type_for_value(value: Any) -> str:
    """Best PG column type for a scalar merge value."""
    if isinstance(value, bool):
        return "BOOLEAN"
    if isinstance(value, (int, float)):
        return "DOUBLE PRECISION"
    return "TEXT"


def open_pg_pool(dsn: str, *, min_size: int = 1, max_size: int = 8, **kwargs: Any) -> Any:
    """Open a psycopg_pool connection pool for server-side concurrent use.

    Sync jobs are single-threaded per user (a plain ``Database`` suffices), but
    the read-only ask server handles concurrent requests, and per-call
    connections should come from a shared pool rather than a new TCP+auth each
    time. The pool is opened lazily per connection slot and created on first
    use.
    """
    import psycopg
    from psycopg_pool import ConnectionPool

    return ConnectionPool(
        dsn,
        min_size=min_size,
        max_size=max_size,
        open=True,
        configure=lambda conn: setattr(conn, "row_factory", psycopg.rows.dict_row),
        **kwargs,
    )


class PostgresBackend:
    """Postgres dialect: ``?`` → ``%s``, information_schema introspection.

    Connections are bound to a ``user_id``: after connect, ``SET app.user_id``
    is applied at the session level so Row-Level Security scopes every
    transaction on that connection to the account.
    """

    name = "postgres"

    def __init__(self, dsn: str, *, user_id: int | None = None) -> None:
        self.dsn = dsn
        self.user_id = user_id

    def connect(self) -> Any:
        import psycopg

        conn = psycopg.connect(self.dsn)
        conn.row_factory = psycopg.rows.dict_row
        if self.user_id is not None:
            conn.execute(
                "SELECT set_config('app.user_id', %s, false)", (str(self.user_id),)
            )
        return conn

    def create_schema(self, conn: Any) -> None:
        for statement in _SCHEMA_PG.split(";"):
            statement = statement.strip()
            if statement:
                conn.execute(statement)
        _ensure_rls(conn)

    def table_info(self, conn: Any, table: str) -> list[dict[str, Any]]:
        rows = conn.execute(
            "SELECT column_name AS name, data_type AS type "
            "FROM information_schema.columns WHERE table_name = %s "
            "ORDER BY ordinal_position",
            (table,),
        ).fetchall()
        return [dict(r) for r in rows]

    def ensure_columns(
        self,
        conn: Any,
        table: str,
        columns: list[str],
        types: dict[str, str] | None = None,
    ) -> None:
        existing = {r["name"] for r in self.table_info(conn, table)}
        for col in columns:
            if col in existing:
                continue
            column_type = (types or {}).get(col) or "DOUBLE PRECISION"
            conn.execute(f"ALTER TABLE {table} ADD COLUMN {col} {column_type}")

    def adapt_sql(self, sql: str) -> str:
        return sql.replace("?", "%s")


def _current_user_id_sql() -> str:
    """SQL snippet for the RLS-scoped current account (0 when unset)."""
    return (
        "COALESCE(NULLIF(current_setting('app.user_id', true), '')::bigint, 0)"
    )


def _start_index(
    filled: list[int],
    *,
    recent_days: int = 30,
    good_fraction: float = 0.5,
    min_good: int = 3,
    lookahead: int = 13,
    min_window: int = 7,
    min_window_good: float = 0.9,
) -> int:
    """Index of the earliest date whose following days are sustained good data.

    A date is good when its filled count reaches ``good_fraction`` of the
    median over the last ``recent_days`` (floor ``min_good``). The start date
    is the first date that is followed by a mostly-good run: ``lookahead`` days
    after it (truncated at the end), of which at least ``min_window_good`` must
    be good.

    So a sparse first day is still the start when the data continues properly
    right after it — a lone null day is confirmed by checking the next ~13
    days, not trimmed — while a genuinely junk prefix pushes the start forward
    to where the good run begins. Returns -1 when there is too little data to
    judge.
    """
    n = len(filled)
    if n < min_window:
        return -1
    recent = filled[-recent_days:]
    reference = sorted(recent)[len(recent) // 2]
    threshold = max(min_good, good_fraction * reference)
    good = [value >= threshold for value in filled]
    for i in range(n):
        following = good[i + 1 : i + 1 + lookahead]
        if len(following) < min_window:
            continue
        if sum(following) / len(following) >= min_window_good:
            return i
    return -1


def _analyze_start(
    conn: Any,
    *,
    recent_days: int = 30,
    good_fraction: float = 0.5,
    min_good: int = 3,
    lookahead: int = 13,
    min_window: int = 7,
    min_window_good: float = 0.9,
) -> str | None:
    """Recommended start date from a user-bound connection (RLS-scoped).

    ``conn`` must already have ``app.user_id`` set so Row-Level Security
    scopes the read to one account. Shared with ``Database.recommend_start_date``
    (which passes its own bound connection).
    """
    cols = [
        r["name"]
        for r in conn.execute(
            "SELECT column_name AS name FROM information_schema.columns "
            "WHERE table_name = 'daily_metrics' AND column_name NOT IN "
            "('user_id', 'calendar_date', 'fetched_at') ORDER BY ordinal_position"
        ).fetchall()
    ]
    if not cols:
        return None
    filled_sql = " + ".join(
        f'(CASE WHEN "{c}" IS NOT NULL THEN 1 ELSE 0 END)' for c in cols
    )
    rows = conn.execute(
        f"SELECT calendar_date, ({filled_sql}) AS filled "
        "FROM daily_metrics ORDER BY calendar_date"
    ).fetchall()
    if len(rows) < min_window:
        return None
    idx = _start_index(
        [int(r["filled"]) for r in rows],
        recent_days=recent_days,
        good_fraction=good_fraction,
        min_good=min_good,
        lookahead=lookahead,
        min_window=min_window,
        min_window_good=min_window_good,
    )
    if idx < 0:
        return None
    return rows[idx]["calendar_date"]


def refine_user_start(
    url: str,
    user_id: int,
    current_start: str | None = None,
    **kwargs: Any,
) -> tuple[str, int] | None:
    """Detect a data-poor prefix and prune it (web-sync hook).

    Opens a lightweight user-bound connection (no schema DDL), computes the
    refined start date, and — when it is later than ``current_start`` —
    deletes the raw ``metrics`` + projected ``daily_metrics`` rows before it.
    Returns ``(recommended, deleted)`` or None when there is nothing to trim.
    """
    backend = PostgresBackend(url, user_id=user_id)
    conn = backend.connect()
    try:
        recommended = _analyze_start(conn, **kwargs)
        if not recommended:
            return None
        if current_start and recommended <= current_start:
            return None
        raw = conn.execute(
            "DELETE FROM metrics WHERE user_id = %s AND calendar_date < %s",
            (user_id, recommended),
        ).rowcount
        projected = conn.execute(
            "DELETE FROM daily_metrics WHERE user_id = %s AND calendar_date < %s",
            (user_id, recommended),
        ).rowcount
        conn.commit()
        return recommended, raw + projected
    finally:
        conn.close()


def _ensure_rls(conn: Any) -> None:
    """Enable Row-Level Security + per-user isolation policies on data tables.

    Idempotent: policies are dropped and recreated so a redeployed schema stays
    consistent. The helper function ``_current_user_id()`` is created once; the
    SELECT grant to the read-only agent role is best-effort (the role may not
    exist yet in a fresh database until the role bootstrap has run).
    """
    conn.execute(
        """
        CREATE OR REPLACE FUNCTION _current_user_id() RETURNS bigint
        LANGUAGE sql STABLE AS
        $$ SELECT COALESCE(NULLIF(current_setting('app.user_id', true), '')::bigint, 0) $$
        """
    )
    for table in _RLS_TABLES:
        conn.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        conn.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        conn.execute(f"DROP POLICY IF EXISTS user_isolation ON {table}")
        conn.execute(
            f"""
            CREATE POLICY user_isolation ON {table}
            USING (user_id = _current_user_id())
            WITH CHECK (user_id = _current_user_id())
            """
        )
    conn.execute(
        f"GRANT SELECT ON {', '.join(_AGENT_TABLES)} TO garmin_readonly"
    )


class Database:
    """Per-user storage for raw Garmin data + typed daily projections.

    Postgres-only. A ``Database`` instance is bound to one ``user_id``: every
    write/read carries that account's rows, and the connection applies
    ``SET app.user_id`` so Row-Level Security enforces the same scoping even
    for queries that bypass this class.

    The ``metrics`` table stores the raw payloads for every day-keyed data
    type. ``daily_metrics`` holds the parsed scalar projection (one wide row
    per calendar date); ``activities`` stores raw activity summaries + details
    keyed by activity id.
    """

    def __init__(self, url: str, *, user_id: int | None = None) -> None:
        self._backend = PostgresBackend(url, user_id=user_id)
        self.path = url
        self.user_id = user_id
        self.conn = self._backend.connect()
        self._backend.create_schema(self.conn)
        self._migrate()
        self.conn.commit()

    @classmethod
    def from_url(cls, url: str, *, user_id: int | None = None) -> "Database":
        """Open a Postgres-backed Database from a ``postgres://`` DSN."""
        return cls(url, user_id=user_id)

    def _migrate(self) -> None:
        """Add any columns missing from a legacy/pre-version schema."""
        self._ensure_columns("activities", ["details_json", "details_fetched_at"])
        self._ensure_columns("activities", ["weather_json", "weather_fetched_at"])
        self._ensure_columns(
            "activity_summaries", list(self._ACTIVITY_SUMMARY_COLUMNS)
        )
        self._ensure_columns(
            "activity_detail_series", list(self._ACTIVITY_SERIES_COLUMNS)
        )
        self._ensure_columns("metrics", ["parsed_at"])
        self._ensure_columns("training_plan", ["completed_activity_id"])
        self._ensure_columns("activities", [
            "summary_parsed_at", "details_parsed_at", "weather_parsed_at",
            "splits_json", "splits_fetched_at", "splits_parsed_at",
        ])

    def _ensure_columns(
        self, table: str, columns: list[str], types: dict[str, str] | None = None
    ) -> None:
        self._backend.ensure_columns(
            self.conn, table, columns, types or _PG_MIGRATION_TYPES.get(table, {})
        )

    def _execute(self, sql: str, params: Any = ()) -> Any:
        """Execute SQL with the backend's placeholder dialect."""
        return self.conn.execute(self._backend.adapt_sql(sql), params)

    def _uid(self) -> tuple[int]:
        if self.user_id is None:
            raise RuntimeError("Database is not bound to a user_id")
        return (self.user_id,)

    # -- Generic raw storage -------------------------------------------------

    def upsert_metric(self, data_type: str, payload: dict[str, Any]) -> None:
        """Store the raw payload for one data type on one date (upsert)."""
        (uid,) = self._uid()
        self._execute(
            """
            INSERT INTO metrics (user_id, data_type, calendar_date, raw_json, fetched_at)
            VALUES (?, ?, ?, ?, ?)
            ON CONFLICT(user_id, data_type, calendar_date) DO UPDATE SET
                raw_json = excluded.raw_json,
                fetched_at = excluded.fetched_at
            """,
            (
                uid,
                data_type,
                payload["calendarDate"],
                json.dumps(payload),
                payload.get("fetched_at"),
            ),
        )
        self.conn.commit()

    def stored_dates(self, data_type: str) -> set[str]:
        """Calendar dates already stored for a data type."""
        (uid,) = self._uid()
        return {
            row["calendar_date"]
            for row in self._execute(
                "SELECT calendar_date FROM metrics WHERE user_id = ? AND data_type = ?",
                (uid, data_type),
            )
        }

    def stored_fetches(self, data_type: str) -> dict[str, str]:
        """Map each stored calendar date to its fetched_at timestamp."""
        (uid,) = self._uid()
        return {
            row["calendar_date"]: row["fetched_at"]
            for row in self._execute(
                "SELECT calendar_date, fetched_at FROM metrics "
                "WHERE user_id = ? AND data_type = ?",
                (uid, data_type),
            )
        }

    def max_calendar_date(self, data_type: str) -> str | None:
        """Highest stored calendar date for a data type, or None."""
        (uid,) = self._uid()
        return self._execute(
            "SELECT MAX(calendar_date) AS max_date FROM metrics "
            "WHERE user_id = ? AND data_type = ?",
            (uid, data_type),
        ).fetchone()["max_date"]

    def metrics_rows(self, data_type: str) -> list[dict[str, Any]]:
        """Raw metric rows (calendar_date, raw_json, fetched_at) for a type."""
        (uid,) = self._uid()
        rows = self._execute(
            "SELECT calendar_date, raw_json, fetched_at FROM metrics "
            "WHERE user_id = ? AND data_type = ? ORDER BY calendar_date",
            (uid, data_type),
        ).fetchall()
        return [dict(r) for r in rows]

    # -- Activities -----------------------------------------------------------

    def upsert_activity(self, payload: dict[str, Any]) -> None:
        activity = payload.get("activity") or payload
        (uid,) = self._uid()
        self._execute(
            """
            INSERT INTO activities (user_id, activity_id, raw_json, fetched_at)
            VALUES (?, ?, ?, ?)
            ON CONFLICT(user_id, activity_id) DO UPDATE SET
                raw_json = excluded.raw_json,
                fetched_at = excluded.fetched_at
            """,
            (
                uid,
                activity["activityId"],
                json.dumps(payload),
                payload.get("fetched_at"),
            ),
        )
        self.conn.commit()

    def stored_activity_ids(self) -> set[int]:
        (uid,) = self._uid()
        return {
            row["activity_id"]
            for row in self._execute(
                "SELECT activity_id FROM activities WHERE user_id = ?", self._uid()
            )
        }

    def set_activity_details(
        self, activity_id: int, details: dict[str, Any], fetched_at: str | None = None
    ) -> None:
        """Store the raw details payload for an activity (upsert)."""
        (uid,) = self._uid()
        self._execute(
            "UPDATE activities SET details_json = ?, details_fetched_at = ? "
            "WHERE user_id = ? AND activity_id = ?",
            (json.dumps(details), fetched_at, uid, activity_id),
        )
        self.conn.commit()

    def set_activity_weather(
        self, activity_id: int, weather: dict[str, Any], fetched_at: str | None = None
    ) -> None:
        """Store the raw weather payload for an activity (upsert)."""
        (uid,) = self._uid()
        self._execute(
            "UPDATE activities SET weather_json = ?, weather_fetched_at = ? "
            "WHERE user_id = ? AND activity_id = ?",
            (json.dumps(weather), fetched_at, uid, activity_id),
        )
        self.conn.commit()

    def activities_missing_weather(self) -> list[int]:
        """Activity ids that have no stored weather payload yet."""
        (uid,) = self._uid()
        rows = self._execute(
            "SELECT activity_id FROM activities "
            "WHERE user_id = ? AND (weather_json IS NULL OR weather_json = '')",
            self._uid(),
        ).fetchall()
        return [r["activity_id"] for r in rows]

    def activity_rows(self) -> list[dict[str, Any]]:
        """Raw activity summary rows (activity_id, raw_json, fetched_at)."""
        (uid,) = self._uid()
        rows = self._execute(
            "SELECT activity_id, raw_json, fetched_at FROM activities "
            "WHERE user_id = ?",
            self._uid(),
        ).fetchall()
        return [dict(r) for r in rows]

    def activity_detail_rows(self) -> list[dict[str, Any]]:
        """Rows with a stored details payload, for the details parser."""
        (uid,) = self._uid()
        rows = self._execute(
            "SELECT activity_id, details_json, details_fetched_at, fetched_at "
            "FROM activities "
            "WHERE user_id = ? AND details_json IS NOT NULL AND details_json != ''",
            self._uid(),
        ).fetchall()
        return [dict(r) for r in rows]

    def activity_weather_rows(self) -> list[dict[str, Any]]:
        """Rows with a stored weather payload, for the weather parser."""
        (uid,) = self._uid()
        rows = self._execute(
            "SELECT activity_id, weather_json, weather_fetched_at FROM activities "
            "WHERE user_id = ? AND weather_json IS NOT NULL AND weather_json != ''",
            self._uid(),
        ).fetchall()
        return [dict(r) for r in rows]

    def set_activity_splits(
        self, activity_id: int, splits: dict[str, Any], fetched_at: str | None = None
    ) -> None:
        """Store the raw splits payload for an activity (upsert)."""
        (uid,) = self._uid()
        self._execute(
            "UPDATE activities SET splits_json = ?, splits_fetched_at = ? "
            "WHERE user_id = ? AND activity_id = ?",
            (json.dumps(splits), fetched_at, uid, activity_id),
        )
        self.conn.commit()

    def activities_missing_splits(self) -> list[int]:
        """Activity ids that have no stored splits payload yet."""
        (uid,) = self._uid()
        rows = self._execute(
            "SELECT activity_id FROM activities "
            "WHERE user_id = ? AND (splits_json IS NULL OR splits_json = '')",
            self._uid(),
        ).fetchall()
        return [r["activity_id"] for r in rows]

    def activity_split_rows(self) -> list[dict[str, Any]]:
        """Rows with a stored splits payload, for the splits parser."""
        (uid,) = self._uid()
        rows = self._execute(
            "SELECT activity_id, splits_json, splits_fetched_at FROM activities "
            "WHERE user_id = ? AND splits_json IS NOT NULL AND splits_json != ''",
            self._uid(),
        ).fetchall()
        return [dict(r) for r in rows]

    def close(self) -> None:
        self.conn.close()

    # -- Daily metrics --------------------------------------------------------

    def merge_daily(
        self, calendar_date: str, values: dict[str, Any],
        fetched_at: str | None = None,
    ) -> None:
        """Merge parsed scalar values into the daily_metrics row for a date.

        Non-null values are written (upserted) keyed by column name. Columns
        not present in every row are created on demand. Existing values for
        the same date/column are overwritten.
        """
        if not values:
            return
        (uid,) = self._uid()
        self._ensure_columns(
            "daily_metrics",
            list(values),
            {col: _pg_type_for_value(value) for col, value in values.items()},
        )
        exists = self._execute(
            "SELECT 1 FROM daily_metrics WHERE user_id = ? AND calendar_date = ?",
            (uid, calendar_date),
        ).fetchone()
        if not exists:
            self._execute(
                "INSERT INTO daily_metrics (user_id, calendar_date) VALUES (?, ?)",
                (uid, calendar_date),
            )
        for col, value in values.items():
            self._execute(
                f"UPDATE daily_metrics SET {col} = ? "
                "WHERE user_id = ? AND calendar_date = ?",
                (value, uid, calendar_date),
            )
        if fetched_at:
            self._execute(
                "UPDATE daily_metrics SET fetched_at = ? "
                "WHERE user_id = ? AND calendar_date = ?",
                (fetched_at, uid, calendar_date),
            )
        self.conn.commit()

    def daily_dates(self) -> set[str]:
        (uid,) = self._uid()
        return {
            row["calendar_date"]
            for row in self._execute(
                "SELECT calendar_date FROM daily_metrics WHERE user_id = ?",
                self._uid(),
            )
        }

    def reset_daily_columns(self) -> list[str]:
        """Drop every data column from ``daily_metrics``, keeping only the keys.

        Used at the start of a full re-parse so the schema always reflects what
        the current parsers produce — stale columns from renamed/removed metrics
        are dropped instead of lingering with NULLs. Columns are recreated on
        demand by ``merge_daily`` as rows are re-parsed. Returns dropped names.
        """
        key = {"user_id", "calendar_date", "fetched_at"}
        cols = [r["name"] for r in self._backend.table_info(self.conn, "daily_metrics")]
        drop = [c for c in cols if c not in key]
        for col in drop:
            self._execute(f"ALTER TABLE daily_metrics DROP COLUMN {col}")
        self.conn.commit()
        return drop

    # -- Pruning ---------------------------------------------------------------
    #
    # Cleanup run after each sync so config changes actually take effect:
    # - ``prune_dates_before`` deletes daily raw + projected rows for dates
    #   before the account's fetch start date (a later start date means older
    #   data is removed, not just left alone).
    # - ``prune_excluded_types`` drops the raw rows of data types that were
    #   newly excluded from the account's sync, and NULLs the projected
    #   daily_metrics columns those types exclusively own (shared columns are
    #   left alone because other enabled types still write them).

    def prune_dates_before(self, calendar_date: str) -> int:
        """Delete all daily rows (raw + projected) before ``calendar_date``."""
        (uid,) = self._uid()
        cur = self._execute(
            "DELETE FROM metrics WHERE user_id = ? AND calendar_date < ?",
            (uid, calendar_date),
        )
        raw_deleted = cur.rowcount
        cur = self._execute(
            "DELETE FROM daily_metrics WHERE user_id = ? AND calendar_date < ?",
            (uid, calendar_date),
        )
        projected_deleted = cur.rowcount
        self.conn.commit()
        return raw_deleted + projected_deleted

    def recommend_start_date(
        self,
        *,
        recent_days: int = 30,
        good_fraction: float = 0.5,
        min_good: int = 3,
        lookahead: int = 13,
        min_window: int = 7,
        min_window_good: float = 0.9,
    ) -> str | None:
        """Earliest date with sustained, normal column coverage, or None.

        Scans ``daily_metrics`` and counts, per calendar date, how many data
        columns are non-NULL. The "normal" level is the median coverage over
        the most recent ``recent_days``; a date counts as good when it reaches
        at least ``good_fraction`` of that level (with a ``min_good`` floor).

        The start date is the first date that is followed by a mostly-good run
        of ``lookahead`` days (see ``_start_index``): a sparse first day is
        confirmed as the start when the data continues properly right after
        it — a lone null day is kept, never trimmed — while a genuinely junk
        prefix pushes the start forward to where the good run begins. Only the
        leading run is ever considered; mid-data dips are never pruned, and a
        low-tracking account is judged against its own recent norm.
        """
        return _analyze_start(
            self.conn,
            recent_days=recent_days,
            good_fraction=good_fraction,
            min_good=min_good,
            lookahead=lookahead,
            min_window=min_window,
            min_window_good=min_window_good,
        )

    def prune_excluded_types(
        self, excluded: list[str], enabled: set[str]
    ) -> int:
        """Delete raw rows + NULL exclusive projected columns for excluded types.

        ``enabled`` is the set of data types still being synced. A column is
        only NULLed when no enabled type can write it, so shared columns
        (e.g. ``resting_hr`` written by heart_rate, sleep, rhr and stats)
        survive the removal of any single source.
        """
        from .parser import TYPE_COLUMNS

        (uid,) = self._uid()
        deleted = 0
        for name in excluded:
            cur = self._execute(
                "DELETE FROM metrics WHERE user_id = ? AND data_type = ?",
                (uid, name),
            )
            deleted += cur.rowcount
        if not excluded:
            self.conn.commit()
            return deleted
        enabled_cols: set[str] = set()
        for name in enabled:
            enabled_cols |= TYPE_COLUMNS.get(name, set())
        exclusive: set[str] = set()
        for name in excluded:
            exclusive |= TYPE_COLUMNS.get(name, set())
        exclusive -= enabled_cols
        if exclusive:
            existing = {
                r["name"] for r in self._backend.table_info(self.conn, "daily_metrics")
            }
            to_null = sorted(exclusive & existing)
            if to_null:
                cols = ", ".join(f"{col} = NULL" for col in to_null)
                self._execute(
                    f"UPDATE daily_metrics SET {cols} WHERE user_id = ?",
                    self._uid(),
                )
        self.conn.commit()
        return deleted

    # -- Parse markers --------------------------------------------------------
    #
    # Incremental parsing: each raw row records the ``fetched_at`` it was last
    # parsed as, so an unchanged row is skipped on the next run. A NULL marker
    # always means "not parsed yet" (first run after the column was added).

    def metric_parsed_at(self, data_type: str) -> dict[str, str | None]:
        """Map each stored date to its last-parsed fetched_at (None = never)."""
        (uid,) = self._uid()
        return {
            row["calendar_date"]: row["parsed_at"]
            for row in self._execute(
                "SELECT calendar_date, parsed_at FROM metrics "
                "WHERE user_id = ? AND data_type = ?",
                (uid, data_type),
            )
        }

    def mark_metric_parsed(self, data_type: str, calendar_date: str) -> None:
        """Record the raw row's current fetched_at as the parse stamp."""
        (uid,) = self._uid()
        self._execute(
            "UPDATE metrics SET parsed_at = fetched_at "
            "WHERE user_id = ? AND data_type = ? AND calendar_date = ?",
            (uid, data_type, calendar_date),
        )

    def activity_parsed_at(self, column: str) -> dict[int, str]:
        """Map each activity id to its last parsed stamp for ``column``."""
        (uid,) = self._uid()
        return {
            row["activity_id"]: row[column]
            for row in self._execute(
                f"SELECT activity_id, {column} FROM activities WHERE user_id = ?",
                self._uid(),
            )
        }

    def mark_activity_parsed(
        self, activity_id: int, marker: str, raw_col: str
    ) -> None:
        """Record the activity's raw ``raw_col`` fetch stamp into ``marker``.

        ``marker`` is one of summary/details/weather parse stamps; ``raw_col``
        is the raw ``activities`` column whose value becomes the marker.
        """
        (uid,) = self._uid()
        self._execute(
            f"UPDATE activities SET {marker} = {raw_col} "
            "WHERE user_id = ? AND activity_id = ?",
            (uid, activity_id),
        )

    # -- Activity summaries ---------------------------------------------------

    _ACTIVITY_SUMMARY_COLUMNS = (
        "activity_name", "activity_type", "start_time_local", "end_time_local",
        "start_date", "duration_hours", "elapsed_hours", "moving_hours",
        "distance_km", "avg_hr", "max_hr", "hr_time_zone_1_pct", "hr_time_zone_2_pct",
        "hr_time_zone_3_pct", "hr_time_zone_4_pct", "hr_time_zone_5_pct",
        "calories",
        "training_load", "aerobic_training_effect", "anaerobic_training_effect",
        "moderate_intensity_minutes", "vigorous_intensity_minutes",
        "elevation_gain_m", "elevation_loss_m", "min_elevation_m",
        "max_elevation_m", "avg_speed_kmh", "max_speed_kmh", "pace_min_km",
        "min_respiration_rate", "avg_respiration_rate", "max_respiration_rate",
        "body_battery_change", "water_estimated_ml", "is_pr",
        "avg_cadence", "max_cadence", "avg_power_w", "max_power_w",
        "norm_power_w", "vo2max",
        "power_time_zone_1_pct", "power_time_zone_2_pct", "power_time_zone_3_pct",
        "power_time_zone_4_pct", "power_time_zone_5_pct",
        "avg_stride_length_cm", "avg_vertical_oscillation_cm",
        "avg_ground_contact_time_ms", "avg_vertical_ratio_pct",
        "weather_temp_c", "weather_apparent_c", "weather_humidity",
        "weather_wind_kmh", "weather_description",
    )

    def upsert_activity_summary(
        self, activity_id: int, values: dict[str, Any], fetched_at: str | None = None
    ) -> None:
        """Insert or replace the curated activity summary row for an id.

        Only non-None values are written; the fixed column set guarantees the
        row always carries the shared summary fields regardless of activity
        type.
        """
        (uid,) = self._uid()
        cols = [c for c in self._ACTIVITY_SUMMARY_COLUMNS if c in values]
        vals = tuple(values[c] for c in cols)
        assignments = ", ".join(f"{c} = excluded.{c}" for c in cols)
        placeholders = ", ".join("?" for _ in cols)
        self._execute(
            f"""
            INSERT INTO activity_summaries (user_id, activity_id, fetched_at, {', '.join(cols)})
            VALUES (?, ?, ?, {placeholders})
            ON CONFLICT(user_id, activity_id) DO UPDATE SET
                {assignments}, fetched_at = excluded.fetched_at
            """,
            (uid, activity_id, fetched_at, *vals),
        )
        self.conn.commit()

    _ACTIVITY_SERIES_COLUMNS = (
        "tick", "ts_ms", "heart_rate", "cadence", "power_w", "speed_kmh",
        "elevation_m", "distance_m", "respiration_rate", "accumulated_power_w",
    )

    def replace_activity_series(
        self, activity_id: int, rows: list[dict[str, Any]]
    ) -> int:
        """Replace the per-tick detail series for one activity.

        The details payload is a fixed schema per activity; re-parsing rebuilds
        the whole tick series, so stale ticks are removed before the new ones
        are written. Returns the number of ticks written.
        """
        (uid,) = self._uid()
        self._execute(
            "DELETE FROM activity_detail_series WHERE user_id = ? AND activity_id = ?",
            (uid, activity_id),
        )
        present = {
            col for row in rows for col in self._ACTIVITY_SERIES_COLUMNS
            if row.get(col) is not None
        }
        cols = [c for c in self._ACTIVITY_SERIES_COLUMNS if c in present]
        placeholders = ", ".join("?" for _ in cols)
        insert = f"""
            INSERT INTO activity_detail_series (user_id, activity_id, {', '.join(cols)})
            VALUES (?, ?, {placeholders})
        """
        written = 0
        if not cols or not rows:
            self.conn.commit()
            return written
        for row in rows:
            vals = tuple(row.get(c) for c in cols)
            self._execute(insert, (uid, activity_id, *vals))
            written += 1
        self.conn.commit()
        return written

    _ACTIVITY_SPLIT_COLUMNS = (
        "split_type", "split_number", "distance_m", "duration_s", "start_time_s",
        "pace_sec_per_km", "avg_hr", "max_hr", "avg_power", "max_power",
        "avg_cadence", "max_cadence", "elevation_gain_m",
    )

    def replace_activity_splits(
        self, activity_id: int, rows: list[dict[str, Any]]
    ) -> int:
        """Replace the per-split projection for one activity.

        The splits payload is re-fetched/re-parsed as a whole, so stale split
        rows are removed before the new ones are written. Returns the number of
        split rows written.
        """
        (uid,) = self._uid()
        self._execute(
            "DELETE FROM activity_splits WHERE user_id = ? AND activity_id = ?",
            (uid, activity_id),
        )
        present = {
            col for row in rows for col in self._ACTIVITY_SPLIT_COLUMNS
            if row.get(col) is not None
        }
        cols = [c for c in self._ACTIVITY_SPLIT_COLUMNS if c in present]
        placeholders = ", ".join("?" for _ in cols)
        insert = f"""
            INSERT INTO activity_splits (user_id, activity_id, {', '.join(cols)})
            VALUES (?, ?, {placeholders})
        """
        written = 0
        if not cols or not rows:
            self.conn.commit()
            return written
        for row in rows:
            vals = tuple(row.get(c) for c in cols)
            self._execute(insert, (uid, activity_id, *vals))
            written += 1
        self.conn.commit()
        return written

    # -- User profile ------------------------------------------------------

    def upsert_profile(
        self, profile_type: str, raw: str, fetched_at: str | None = None
    ) -> None:
        """Store (or overwrite) one profile payload, keyed by profile_type."""
        (uid,) = self._uid()
        self._execute(
            """
            INSERT INTO user_profile (user_id, profile_type, raw_json, fetched_at)
            VALUES (?, ?, ?, ?)
            ON CONFLICT(user_id, profile_type) DO UPDATE SET
                raw_json = excluded.raw_json,
                fetched_at = excluded.fetched_at
            """,
            (uid, profile_type, raw, fetched_at),
        )
        self.conn.commit()

    def get_profile(self, profile_type: str) -> dict[str, Any] | None:
        """Return (raw_json, fetched_at) for a stored profile, or None."""
        (uid,) = self._uid()
        row = self._execute(
            "SELECT raw_json, fetched_at FROM user_profile "
            "WHERE user_id = ? AND profile_type = ?",
            (uid, profile_type),
        ).fetchone()
        return dict(row) if row else None

    def replace_hr_zones(self, rows: list[dict[str, Any]]) -> int:
        """Replace the entire hr_zones table with a fresh per-sport snapshot.

        The heartRateZones endpoint returns one object per sport (DEFAULT,
        RUNNING, CYCLING, ...), each carrying that sport's zone floors. The set
        is replaced as a whole because it represents the current device
        configuration. Returns the number of rows written.
        """
        (uid,) = self._uid()
        self._execute("DELETE FROM hr_zones WHERE user_id = ?", self._uid())
        for row in rows:
            self._execute(
                """
                INSERT INTO hr_zones (
                    user_id, sport, training_method,
                    zone1_min, zone1_max, zone2_min, zone2_max,
                    zone3_min, zone3_max, zone4_min, zone4_max,
                    zone5_min, zone5_max,
                    max_hr_used, resting_hr_used, lactate_threshold_hr_used,
                    resting_hr_auto_update, fetched_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    uid, row["sport"], row.get("training_method"),
                    row.get("zone1_min"), row.get("zone1_max"),
                    row.get("zone2_min"), row.get("zone2_max"),
                    row.get("zone3_min"), row.get("zone3_max"),
                    row.get("zone4_min"), row.get("zone4_max"),
                    row.get("zone5_min"), row.get("zone5_max"),
                    row.get("max_hr_used"), row.get("resting_hr_used"),
                    row.get("lactate_threshold_hr_used"),
                    row.get("resting_hr_auto_update"), row.get("fetched_at"),
                ),
            )
        self.conn.commit()
        return len(rows)

    def replace_race_predictions(self, row: dict[str, Any] | None) -> int:
        """Replace the race-prediction snapshot with a fresh one.

        Race predictions are a current-fitness snapshot (like hr_zones), so the
        single stored row is overwritten entirely. Returns 1 when a row was
        written, else 0.
        """
        (uid,) = self._uid()
        self._execute("DELETE FROM race_predictions WHERE user_id = ?", self._uid())
        if row is None:
            self.conn.commit()
            return 0
        self._execute(
            """
            INSERT INTO race_predictions (
                user_id, calendar_date, time_5k_min, time_10k_min,
                time_half_marathon_min, time_marathon_min, fetched_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                uid, row.get("calendar_date"), row.get("time_5k_min"),
                row.get("time_10k_min"), row.get("time_half_marathon_min"),
                row.get("time_marathon_min"), row.get("fetched_at"),
            ),
        )
        self.conn.commit()
        return 1

    def replace_gear(self, rows: list[dict[str, Any]]) -> int:
        """Replace the entire gear table with a fresh snapshot.

        Gear is a current "what's in your garage right now" snapshot (like
        hr_zones), not history: each sync replaces every row so the table always
        reflects the latest gear list and its stats. Returns the number of rows
        written.
        """
        (uid,) = self._uid()
        self._execute("DELETE FROM gear WHERE user_id = ?", self._uid())
        for row in rows:
            self._execute(
                """
                INSERT INTO gear (
                    user_id, gear_uuid, gear_type, name, total_distance_km,
                    activity_count, last_activity_date, retired, fetched_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    uid, row.get("gear_uuid"), row.get("gear_type"),
                    row.get("name"), row.get("total_distance_km"),
                    row.get("activity_count"), row.get("last_activity_date"),
                    row.get("retired"), row.get("fetched_at"),
                ),
            )
        self.conn.commit()
        return len(rows)

    def replace_power_zones(self, rows: list[dict[str, Any]]) -> int:
        """Replace the entire power_zones table with a fresh per-sport snapshot.

        Power zones are a current device configuration (like hr_zones): the set
        is replaced as a whole each sync. Returns the number of rows written.
        """
        (uid,) = self._uid()
        self._execute("DELETE FROM power_zones WHERE user_id = ?", self._uid())
        for row in rows:
            self._execute(
                """
                INSERT INTO power_zones (
                    user_id, sport,
                    zone1_min, zone1_max, zone2_min, zone2_max,
                    zone3_min, zone3_max, zone4_min, zone4_max,
                    zone5_min, zone5_max, zone6_min, zone6_max,
                    zone7_min, zone7_max,
                    functional_threshold_power, fetched_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    uid, row["sport"],
                    row.get("zone1_min"), row.get("zone1_max"),
                    row.get("zone2_min"), row.get("zone2_max"),
                    row.get("zone3_min"), row.get("zone3_max"),
                    row.get("zone4_min"), row.get("zone4_max"),
                    row.get("zone5_min"), row.get("zone5_max"),
                    row.get("zone6_min"), row.get("zone6_max"),
                    row.get("zone7_min"), row.get("zone7_max"),
                    row.get("functional_threshold_power"), row.get("fetched_at"),
                ),
            )
        self.conn.commit()
        return len(rows)

    def replace_devices(self, rows: list[dict[str, Any]]) -> int:
        """Replace the entire devices table with a fresh snapshot.

        Devices are a current "what's on my account right now" snapshot (like
        gear): each sync replaces every row. Returns the number of rows written.
        """
        (uid,) = self._uid()
        self._execute("DELETE FROM devices WHERE user_id = ?", self._uid())
        for row in rows:
            self._execute(
                """
                INSERT INTO devices (
                    user_id, device_id, model_name, display_name, fetched_at
                ) VALUES (?, ?, ?, ?, ?)
                """,
                (
                    uid, row.get("device_id"), row.get("model_name"),
                    row.get("display_name"), row.get("fetched_at"),
                ),
            )
        self.conn.commit()
        return len(rows)

    # -- Derived metrics -------------------------------------------------------

    def replace_derived_metrics(self, rows: list[dict[str, Any]]) -> int:
        """Replace the entire ``derived_metrics`` series for one user.

        Derived metrics (readiness, ACWR, ...) are recomputed from source
        tables and stored wholesale each sync, so the table is replaced rather
        than merged — the stored series always reflects the current algorithm.
        Each row is {calendar_date, metric, value, qualifier, fetched_at}.
        Returns the number of rows written.
        """
        (uid,) = self._uid()
        self._execute("DELETE FROM derived_metrics WHERE user_id = ?", self._uid())
        if not rows:
            self.conn.commit()
            return 0
        for row in rows:
            self._execute(
                "INSERT INTO derived_metrics "
                "(user_id, calendar_date, metric, value, qualifier, fetched_at) "
                "VALUES (?, ?, ?, ?, ?, ?)",
                (
                    uid, row["calendar_date"], row["metric"],
                    row["value"], row.get("qualifier"), row.get("fetched_at"),
                ),
            )
        self.conn.commit()
        return len(rows)

    # -- Sync state -----------------------------------------------------------

    def get_state(self, key: str) -> str | None:
        (uid,) = self._uid()
        row = self._execute(
            "SELECT value FROM sync_state WHERE user_id = ? AND key = ?",
            (uid, key),
        ).fetchone()
        return row["value"] if row else None

    def set_state(self, key: str, value: str) -> None:
        (uid,) = self._uid()
        self._execute(
            """
            INSERT INTO sync_state (user_id, key, value) VALUES (?, ?, ?)
            ON CONFLICT(user_id, key) DO UPDATE SET value = excluded.value
            """,
            (uid, key, value),
        )
        self.conn.commit()


def init_db(user_id: int | None = None) -> Database:
    """Create/open the per-user database using configuration.

    Postgres is the only runtime (``GARMIN_DB_URL``). ``user_id`` defaults to
    ``GARMIN_LOCAL_USER_ID`` (single-user installs) when not given.
    """
    config = load_config()
    url = config["db_url"]
    if not url:
        raise RuntimeError(
            "GARMIN_DB_URL must be set (Postgres is the only supported backend)"
        )
    uid = user_id or config.get("local_user_id") or 1
    return Database.from_url(url, user_id=uid)


def ensure_schema(url: str) -> None:
    """Idempotently create the full schema (tables, RLS, grants) on one DSN.

    Runs the same ``create_schema`` a ``Database`` would on connect, without
    binding to a user — used by the server at startup so user-facing tables
    (e.g. ``training_plan``) exist before the first sync ever runs.
    """
    backend = PostgresBackend(url)
    conn = backend.connect()
    try:
        backend.create_schema(conn)
        backend.ensure_columns(
            conn, "training_plan", ["completed_activity_id"],
            {"completed_activity_id": "BIGINT"},
        )
        conn.commit()
    finally:
        conn.close()
